version: '3.8'

services:

  # frontend:
  #   image: node:20-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app    # Mount the local frontend directory into the container
  #     - /app/node_modules
  #   ports:
  #     - "3000:5173"
  #   command: sh -c "npm install && npm run dev"
  #   depends_on:
  #     - backend
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: graphdb
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3304:3306"
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     timeout: 20s
  #     retries: 10

  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    ports:
      - "9999:8080"
    restart: unless-stopped
    volumes:
      - blazegraph_data:/data
  # backend:
  #   build: ./backend
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./backend:/app     # Mount the local backend directory into the container
  #     - /app/venv
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     # db:
  #     #   condition: service_healthy
  #     blazegraph:
  #       condition: service_started

      
  
volumes:
  # mysql_data:
  blazegraph_data: